# Site settings
title: AsylumConnect Catalog
email: tiff@asylumconnect.org
description: > # this means to ignore newlines until "baseurl:"
  AsylumConnect is a volunteer initiative that seeks to provide
  LGBTQ asylum seekers in the U.S. with lifesaving online informational resources.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://asylumconnectcatalog.com" # the base hostname & protocol for your site
github_username:  asylumconnect

# Build settings
markdown: kramdown

collections:
  - seattle
